<<<<<<< HEAD
{{- if .Values.backend.aws.enabled }}
=======
{{- if .Values.global.aws.enabled }}
>>>>>>> d769a6f396946c315c21c62a7253c80b5962416e
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openrag.fullname" . }}-aws
  namespace: {{ include "openrag.namespace" . }}
  labels:
    {{- include "openrag.labels" . | nindent 4 }}
type: Opaque
stringData:
<<<<<<< HEAD
  access-key-id: {{ .Values.backend.aws.accessKeyId | quote }}
  secret-access-key: {{ .Values.backend.aws.secretAccessKey | quote }}
=======
  access-key-id: {{ .Values.global.aws.accessKeyId | quote }}
  secret-access-key: {{ .Values.global.aws.secretAccessKey | quote }}
>>>>>>> d769a6f396946c315c21c62a7253c80b5962416e
{{- end }}
